### ISSUE TITLE
Custom messages  in String::Validator::Password is not documented and appending values unnecessarily

### ISSUE THREAD

**Issue by Virendrabaskar** [brainbuz/String-Validator#5]
```
custom_messages => {
            common_tooshort => "At least $min_length characters is required"
 }
```

After I gave my own message into the new method,  The code is appending the values at the end of my message.

**Comment by brainbuz** [comment]
I added a test to password that demonstrates how to do this and noted it in the documentation of string validator. You should be able to pull the new trial from cpan soon or you can look at test 40-messages here for a working example.

**Comment by brainbuz** [comment]
v 2.01 of String::Validator::Password has been live on CPAN for 3 days. If you are still having an issue, please submit a test or sample code demonstrating the issue.
